# swagger.yml

openapi: 3.0.0
info:
  title: "Spotify Analysis REST API"
  description: "An API about people's spotify listening habits."
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /song_data:
    get:
      operationId: "main.all_time_song_info_wrapper"
      tags:
        - "Song Info"
      summary: "Read the list of top 10% all time song listening."
      responses:
        "200":
          description: "Successfully read song list"